// Турецкий
const tr = {
	// registration
	'SignInForm#1': 'Sign In',
	'SignInForm#2': 'Your email',
	'SignInForm#3': 'Password',
	'SignInForm#4': 'Do you have an account?',
	'SignInForm#5': 'Sign Up',
	'SignInForm#6': 'Demo',

	'SignUpForm#1': 'SIGN UP',
	'SignUpForm#2': 'Your name',
	'SignUpForm#3': 'Your surname',
	'SignUpForm#4': 'Your email',
	'SignUpForm#5': 'Password (min 8 characters)',
	'SignUpForm#6': 'I give my consent to process and store my personal data for the purpose of verifying my identity.',
	'SignUpForm#7': '* Required',
	'SignUpForm#8': 'Already have an account?',
	'SignUpForm#9': 'Sign In',

	'CheckEmailForm#1': 'Please, check your email',
	'CheckEmailForm#2': 'We have sent you instructions to reset your password.',
	'CheckEmailForm#3': 'Return to',
	'CheckEmailForm#4': 'Sign In',

	'ResetPasswordForm#1': 'Reset Your Password',
	'ResetPasswordForm#2': 'We’ll email you instructions to reset your password.',
	'ResetPasswordForm#3': 'Your email',
	'ResetPasswordForm#4': 'Return to Sign In',
	'ResetPasswordForm#5': 'Sign In',

	'RegistrationPage#1': '© 2018 Cindx',
	'RegistrationPage#2': 'Privacy Policy',
	'RegistrationPage#3': 'Terms of Service',

	'Input#1': 'Forgot?',

	// marketplace
	'MarketplacePageContainer#1': 'Product Card is a asset manager\'s strategy which investor can select and follow',
	'MarketplacePageContainer#2': 'Trading history generated by strategy',
	'MarketplacePageContainer#3': 'Exchange where the product is allocated. In this case on Binance',
	'MarketplacePageContainer#4': 'Asset manager who creates this strategy to follow',
	'MarketplacePageContainer#5': 'Basic asset',
	'MarketplacePageContainer#6': 'Profitability of the strategy',
	'MarketplacePageContainer#7': 'The period of implementation',
	'MarketplacePageContainer#8': 'The fees to be paid to asset manager for successful trades',
	'MarketplacePageContainer#9': 'The number of investors who follow this strategy',

	'TraderCardList#1': 'Week',
	'TraderCardList#2': 'Month',
	'TraderCardList#3': 'Months',
	'TraderCardList#4': 'Horizon',
	'TraderCardList#5': 'Fees',
	'TraderCardList#6': 'Investors',

	// terminal
	'FillOrders#1': 'ORDER DATE',
	'FillOrders#2': 'PRICE',
	'FillOrders#3': 'QUANTITY',

	'OpenOrderList#1': 'Close',

	'OpenOrders#1': 'PRICE',
	'OpenOrders#2': 'VOLUME',
	'OpenOrders#3': 'TOTAL',

	'OrderBook#1': 'PRICE EUR',
	'OrderBook#2': 'VOLUME',
	'OrderBook#3': 'TOTAL',
	'OrderBook#4': 'ORDER BOOK',

	'OrdersTerminal#1': 'OPEN ORDERS',
	'OrdersTerminal#2': 'FILL ORDERS',
	
	'OrderTimer#1': 'w',
	'OrderTimer#2': 'd',
	'OrderTimer#3': 'h',
	'OrderTimer#4': 'm',
	'OrderTimer#5': 's',

	'TerminalDateFilter#1': '4 HOUR',
	'TerminalDateFilter#2': '1 DAY',
	'TerminalDateFilter#3': '1 WEEK',

	'TerminalForm#1': 'Quantity',
	'TerminalForm#2': 'Price',
	'TerminalForm#3': 'PLACE',
	'TerminalForm#4': 'ORDER',

	'TerminalFormContainer#1': 'ORDER_LIMIT_SUCCESS',
	'TerminalFormContainer#2': 'ORDER_LIMIT_ERR',
	'TerminalFormContainer#3': 'In demo mode, you can not place orders, sorry.',

	'TerminalHead#1': 'Line',
	'TerminalHead#2': 'Candles',

	'TradeHistory#1': 'Trade Size',
	'TradeHistory#2': 'Price',
	'TradeHistory#3': 'Time',
	'TradeHistory#4': 'TRADE HISTORY',

	'TerminalPageContainer#1': 'Exchange selector. Binance is selected. But will be able to select from the list of:  Binance Abucoins Bitfinex Bitthumb Bitstamp Bittrex Bleutrade Cryptopia Gdax Gemini HitBTC Huobi Kraken KuCoin Livecoin Okex Poloniex Bitmex Exmo',
	'TerminalPageContainer#2': 'Assets pair selected to trade on Binance',
	'TerminalPageContainer#3': 'Chart type. You can choose line or Japanese candles',
	'TerminalPageContainer#4': 'Order book shows the demand and supply for the current asset on Binance',
	'TerminalPageContainer#5': 'All the last trades for the pair on Binance provided real time',
	'TerminalPageContainer#6': 'Here are the charts which provide the price dynamics of selected asset on Binance',
	'TerminalPageContainer#7': 'The list of open and filled by trader orders on Binance',
	'TerminalPageContainer#8': 'Here you can arrange the trade operations on Binance',

	// profile
	'AddProduct#1': 'Add Product',

	'Apis#1': 'You need to add new API Keys',
	'Apis#2': 'CURRENT FUND’S API',

	'ListProducts#1': 'You need to add new API Keys',
	'ListProducts#2': 'Current Fund’s API',
	'ListProducts#3': 'Where to get API Key?',
	'ListProducts#4': 'Add new API',

	'LogOut#1': 'LOG OUT',

	'Products#1': 'CONNECTED PRODUCTS',

	'ProfilePage#1': 'YOUR INVESTORS',

	'ProfilePageContainer#1': 'The overall size of portfolio',
	'ProfilePageContainer#2': 'The overall performance chart',
	'ProfilePageContainer#3': 'The strategies implemented',
	'ProfilePageContainer#4': 'The overall size of portfolio',
	'ProfilePageContainer#5': 'The overall performance chart',
	'ProfilePageContainer#6': 'Exchanges where the wallet is allocated',

	// kyc
	'KycPage#1': 'KYC Accaunt verification',
	'KycPage#2': '© 2018 CryptoActive',
	'KycPage#3': 'Privacy Policy',
	'KycPage#4': 'Terms of Service',

	'KycStep1#1': 'I give my consent to process and store my personal data for the purpose of verifying my identity.',
	'KycStep1#2': 'I give my consent to process my personal data for the purposes and conditions set out in the',
	'KycStep1#3': 'Privacy Policy',
	'KycStep1#4': 'Skip this Step',
	'KycStep1#5': 'Choose your country',

	'KycStep2#1': 'Proof of identity',
	'KycStep2#2': 'Selfie with the proof',
	'KycStep2#3': 'Proof of adress',
	'KycStep2#4': 'Please take a photo of your passport. The photo should be bright and clear, and all corners of your document must be visible.',
	'KycStep2#5': 'Go Back',
	'KycStep2#6': 'Proceed',

	// common
	'PopUpComingSoon#1': 'Buy CINX tokens to help our project development.',
	'PopUpComingSoon#2': 'Buy CINX tokens to help our project development.',

	'PopUpNewProduct#1': 'NEW PRODUCT',
	'PopUpNewProduct#2': 'Where to get API Key?',
	'PopUpNewProduct#3': 'Name of product (50 characters maximum)',
	'PopUpNewProduct#4': 'API Key',
	'PopUpNewProduct#5': 'secret key',
	'PopUpNewProduct#6': 'Description of your strategy min 250 characters',
	'PopUpNewProduct#7': 'Add Product',

	'PopUpProductPage#1': 'Horizon',
	'PopUpProductPage#2': 'Fees',
	'PopUpProductPage#3': 'Investors',
	'PopUpProductPage#4': 'Connect Now',
	'PopUpProductPage#5': 'Disconnect',

	'PopUpRegistration#1': 'Registration',
	'PopUpRegistration#2': 'Register to access the basic functions of the product. There is also a transition to the demo mode.',
	'PopUpRegistration#3': 'Already have an account?',
	'PopUpRegistration#4': 'Join now',
	'PopUpRegistration#5': 'Sign In',

	'Profile#1': 'The overall size of portfolio',
	'Profile#2': 'The overall performance chart',
	'Profile#3': 'The strategies implemented',
	'Profile#4': 'The overall size of portfolio',
	'Profile#5': 'The overall performance chart',
	'Profile#6': 'Exchanges where the wallet is allocated',

	'MobileStub#1': 'Ekip ürün hakkında konuşuyor',
	'MobileStub#2': 'Videoyu izle',
	'MobileStub#3': 'Satış öncesi katılın',
	'MobileStub#4': 'Bizi takip et:',
	'MobileStub#5': 'MVP sadece masaüstünde mevcuttur',

	//тут гугл транслате был))
	'Menu#1': 'Terminal',
	'Menu#2': 'Marketplace',
	'Menu#3': 'Profile',

}

export default tr;